name: cocktail_app
description: Cocktail of the day application
version: 1.0.0+1
authors:
  - Flutter Mobile developer cource

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  http: ^0.12.2
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.18.1

dev_dependencies:
  test: ^1.15.7

  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  pedantic: ^1.9.0
  build_runner: ^1.10.1
  json_serializable: ^3.4.1

flutter:
  uses-material-design: true

