name: cocktail_app
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1
  http: ^0.12.2
  meta: any

dev_dependencies:
  test: ^1.15.7



  pedantic: ^1.9.0
  build_runner: ^1.10.1
  json_serializable: ^3.4.1
  fake_async: ^1.1.0  # use this package to wrap timers and futures to controlled zones
  mockito: ^4.1.3 # use this package if you want to use mocks instead of using real instances of dependencies